"""
SentinelOps email templates for task notifications.
Each template returns (subject, text_body, html_body).
"""

import os
from html import escape
from typing import Iterable, Optional, Tuple
from urllib.parse import quote

FRONTEND_URL = os.getenv("FRONTEND_URL", os.getenv("API_BASE_URL", "http://localhost:3000"))


def _task_link(task_id: str) -> str:
    return f"{FRONTEND_URL.rstrip('/')}/tasks?task={quote(str(task_id))}"


def _text_body(
    headline: str,
    lines: Iterable[str],
    metadata: Iterable[Tuple[str, str]],
    cta_label: str,
    link: str
) -> str:
    meta_lines = [f"{label}: {value}" for label, value in metadata if value]
    parts = ["SentinelOps", headline, ""]
    parts.extend(lines)
    if meta_lines:
        parts.append("")
        parts.extend(meta_lines)
    parts.extend(["", f"{cta_label}: {link}", "", "SentinelOps Command Center"])
    return "\n".join(parts)


def _html_body(
    *,
    badge: str,
    headline: str,
    intro: str,
    lines: Iterable[str],
    metadata: Iterable[Tuple[str, str]],
    cta_label: str,
    link: str,
    accent: str,
) -> str:
    safe_badge = escape(badge)
    safe_headline = escape(headline)
    safe_intro = escape(intro)
    safe_link = escape(link, quote=True)
    safe_cta = escape(cta_label)

    line_html = "".join(
        f'<p style="margin:0 0 12px;color:#cbd5e1;font-size:15px;line-height:1.7;">{escape(line)}</p>'
        for line in lines
    )
    metadata_html = "".join(
        (
            '<tr>'
            f'<td style="padding:10px 0;color:#94a3b8;font-size:12px;letter-spacing:0.08em;'
            f'text-transform:uppercase;border-bottom:1px solid rgba(148,163,184,0.14);">{escape(label)}</td>'
            f'<td style="padding:10px 0;color:#e2e8f0;font-size:14px;text-align:right;'
            f'border-bottom:1px solid rgba(148,163,184,0.14);">{escape(value)}</td>'
            '</tr>'
        )
        for label, value in metadata
        if value
    )

    return f"""\
<!DOCTYPE html>
<html>
  <body style="margin:0;padding:24px;background:#020617;font-family:'Segoe UI','Helvetica Neue',Arial,sans-serif;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:680px;margin:0 auto;border-collapse:separate;border-spacing:0;">
      <tr>
        <td style="padding:0;">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0"
            style="background:linear-gradient(180deg,#08111f 0%,#0f172a 100%);border:1px solid rgba(56,189,248,0.14);border-radius:24px;overflow:hidden;box-shadow:0 24px 64px rgba(2,6,23,0.48);">
            <tr>
              <td style="padding:0;background:linear-gradient(135deg,{accent} 0%,#0f172a 85%);">
                <div style="padding:28px 32px 30px;">
                  <div style="display:inline-block;padding:7px 12px;border-radius:999px;background:rgba(255,255,255,0.14);color:#e2e8f0;font-size:11px;font-weight:700;letter-spacing:0.16em;text-transform:uppercase;">
                    {safe_badge}
                  </div>
                  <div style="margin-top:18px;color:#ffffff;font-size:30px;font-weight:800;line-height:1.15;letter-spacing:-0.03em;">
                    {safe_headline}
                  </div>
                  <div style="margin-top:12px;color:#dbeafe;font-size:15px;line-height:1.7;max-width:520px;">
                    {safe_intro}
                  </div>
                </div>
              </td>
            </tr>
            <tr>
              <td style="padding:28px 32px 18px;">
                {line_html}
                <div style="margin:20px 0 24px;">
                  <a href="{safe_link}" style="display:inline-block;padding:13px 20px;border-radius:14px;background:{accent};color:#020617;text-decoration:none;font-size:14px;font-weight:800;letter-spacing:0.02em;">
                    {safe_cta}
                  </a>
                </div>
                <table role="presentation" width="100%" cellspacing="0" cellpadding="0"
                  style="border-collapse:collapse;padding:16px 18px;background:rgba(15,23,42,0.72);border:1px solid rgba(148,163,184,0.14);border-radius:18px;">
                  <tr>
                    <td colspan="2" style="padding:0 0 12px;color:#f8fafc;font-size:13px;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;">
                      Operational Snapshot
                    </td>
                  </tr>
                  {metadata_html}
                </table>
              </td>
            </tr>
            <tr>
              <td style="padding:0 32px 26px;color:#64748b;font-size:12px;line-height:1.6;">
                This message was generated by SentinelOps to keep task coordination visible across email and in-app channels.
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>
"""


def _build_template(
    *,
    subject: str,
    badge: str,
    headline: str,
    intro: str,
    lines: Iterable[str],
    metadata: Iterable[Tuple[str, str]],
    cta_label: str = "Open task in SentinelOps",
    task_id: str,
    accent: str = "#38bdf8",
) -> Tuple[str, str, str]:
    link = _task_link(task_id)
    text = _text_body(headline, lines, metadata, cta_label, link)
    html = _html_body(
        badge=badge,
        headline=headline,
        intro=intro,
        lines=lines,
        metadata=metadata,
        cta_label=cta_label,
        link=link,
        accent=accent,
    )
    return subject, text, html


def assignment_template(
    recipient_name: Optional[str],
    task_title: str,
    task_id: str,
    actor_name: Optional[str] = None
) -> Tuple[str, str, str]:
    actor = actor_name or "A SentinelOps teammate"
    headline = f'{actor} assigned "{task_title}"'
    intro = f"{recipient_name or 'Team member'}, a task has just entered your queue."
    lines = [
        f'{actor} assigned you the task "{task_title}".',
        "Open the task to review the brief, timeline, and next actions.",
    ]
    metadata = [("Task", task_title), ("Assigned by", actor), ("Task ID", task_id)]
    return _build_template(
        subject=f"SentinelOps | Task assigned: {task_title}",
        badge="Task Assignment",
        headline=headline,
        intro=intro,
        lines=lines,
        metadata=metadata,
        task_id=task_id,
        accent="#22c55e",
    )


def comment_template(
    task_title: str,
    task_id: str,
    comment_text: str,
    actor_name: Optional[str] = None
) -> Tuple[str, str, str]:
    actor = actor_name or "A SentinelOps teammate"
    preview = comment_text.strip().replace("\n", " ")
    if len(preview) > 180:
        preview = f"{preview[:177]}..."
    lines = [
        f'{actor} added a new comment on "{task_title}".',
        f'Latest note: "{preview}"',
    ]
    metadata = [("Task", task_title), ("Commented by", actor), ("Task ID", task_id)]
    return _build_template(
        subject=f"SentinelOps | New comment on {task_title}",
        badge="Task Commentary",
        headline=f'New task comment on "{task_title}"',
        intro="Discussion activity has been recorded on this task.",
        lines=lines,
        metadata=metadata,
        task_id=task_id,
        accent="#38bdf8",
    )


def attachment_template(
    task_title: str,
    task_id: str,
    filename: str,
    actor_name: Optional[str] = None
) -> Tuple[str, str, str]:
    actor = actor_name or "A SentinelOps teammate"
    lines = [
        f'{actor} uploaded "{filename}" to "{task_title}".',
        "Review the attachment inside the task thread to keep context and approvals aligned.",
    ]
    metadata = [("Task", task_title), ("Attachment", filename), ("Uploaded by", actor)]
    return _build_template(
        subject=f"SentinelOps | Attachment added to {task_title}",
        badge="Task Evidence",
        headline=f'New attachment on "{task_title}"',
        intro="Supporting material has been added to this task record.",
        lines=lines,
        metadata=metadata,
        task_id=task_id,
        accent="#f59e0b",
    )


def created_template(
    task_title: str,
    task_id: str,
    actor_name: Optional[str] = None
) -> Tuple[str, str, str]:
    actor = actor_name or "You"
    lines = [
        f'{actor} created the task "{task_title}".',
        "The task is now available in SentinelOps for execution, updates, and evidence capture.",
    ]
    metadata = [("Task", task_title), ("Created by", actor), ("Task ID", task_id)]
    return _build_template(
        subject=f"SentinelOps | Task created: {task_title}",
        badge="Task Created",
        headline=f'"{task_title}" is now live',
        intro="A new operational task has been opened in SentinelOps.",
        lines=lines,
        metadata=metadata,
        task_id=task_id,
        accent="#22c55e",
    )


def status_change_template(
    task_title: str,
    task_id: str,
    old_status: str,
    new_status: str,
    actor_name: Optional[str] = None
) -> Tuple[str, str, str]:
    actor = actor_name or "A SentinelOps teammate"
    lines = [
        f'{actor} changed "{task_title}" from {old_status} to {new_status}.',
        "Open the task to review the latest context, comments, and supporting evidence.",
    ]
    metadata = [
        ("Task", task_title),
        ("Previous status", old_status),
        ("Current status", new_status),
        ("Updated by", actor),
    ]
    return _build_template(
        subject=f"SentinelOps | Status updated: {task_title}",
        badge="Task Status",
        headline=f'"{task_title}" moved to {new_status}',
        intro="Task execution state changed in SentinelOps.",
        lines=lines,
        metadata=metadata,
        task_id=task_id,
        accent="#06b6d4",
    )
